In [1]:
import numpy as np
a = np.array([2,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[2 3 4 5]
<class 'numpy.ndarray'>
1
(4,)


In [2]:
a = np.array([2+1j , 3, 4 , 5],dtype=complex)
print(a)

[2.+1.j 3.+0.j 4.+0.j 5.+0.j]


In [8]:
datetime1=np.array(['2023-03-03T12:00:00','2023-06-07T03:01:00'],dtype="datetime64")
a=np.diff(datetime1)
print(a.dtype)
print(datetime1.dtype)

timedelta64[s]
datetime64[s]


In [10]:
from numpy import random
s = random.rand()
b = random.randint([2,3,4,5])
print(s)
print(b)

0.9718944980667367
[1 1 2 3]


In [12]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.ones((2,3,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [24]:
a = np.arange(20,69,2)
print(a)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68]


In [25]:
a = np.linspace(1,2,100)
print(a)

[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636 1.37373737 1.38383838 1.39393939 1.4040404  1.41414141
 1.42424242 1.43434343 1.44444444 1.45454545 1.46464646 1.47474747
 1.48484848 1.49494949 1.50505051 1.51515152 1.52525253 1.53535354
 1.54545455 1.55555556 1.56565657 1.57575758 1.58585859 1.5959596
 1.60606061 1.61616162 1.62626263 1.63636364 1.64646465 1.65656566
 1.66666667 1.67676768 1.68686869 1.6969697  1.70707071 1.71717172
 1.72727273 1.73737374 1.74747475 1.75757576 1.76767677 1.77777778
 1.78787879 1.7979798  1.80808081 1.81818182 1.82828283 1.83838384
 1.84848485 1.85858586 1.86868687 1.87878788 1.88888889 1.89898

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
print(A*B)
print(A@B)
c = A.dot(B)
print(c)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
